//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bronirovanie_Diplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id_booking { get; set; }
        public int id_employeer { get; set; }
        public int id_table { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Number_of_seats { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Number { get; set; }
        public string Discount { get; set; }
        public string Description { get; set; }
    
        public virtual Employeer Employeer { get; set; }
        public virtual Table Table { get; set; }
    }
}
