//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bronirovanie_Diplom.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Employeer> Employeer { get; set; }
        public virtual DbSet<Gost> Gost { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Table_Svobodnie> Table_Svobodnie { get; set; }
        public virtual DbSet<Table_zaniti> Table_zaniti { get; set; }
    }
}
