//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bronirovanie_Diplom.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_zaniti
    {
        public int id_zanzti { get; set; }
        public int Number_of_seats { get; set; }
    }
}
